name: Build, Package, Release (build-pipeline.yaml)
description: Build and release a Docker image for AMD64 architecture without semantic release.
'on':
  release:
    types:
      - created
  push:
    branches:
      - dev
env:
  VERSION: 0.0.1
  MO_DOCKERFILE: Dockerfile
  MO_DOCKERCONTEXT: .
  MO_REGISTRY_AUTH_URL: https://ghcr.io
  MO_REGISTRY_URL: ghcr.io/janlepsky
  MO_IMAGE_NAME: myapp
  MO_API_KIND: workspace
  MO_API_TOKEN_EXPIRES_AT__E66FE16DB2B8712F08B6: '2299-06-05T08:08:55.000Z'
  MO_SERVICE__E66FE16DB2B8712F08B6: H4sIAAAAAAAAA12MTW7DIBQG7/KtjRpswD/rbLrpHR7wEqHYgMBOm0a5e+W0yqLbGc3ckcqZYvimNaT47jHh1HetM4pE1ysjlG9ZWGudUMNhJK0k+96hgZu3unJ5Jgdvda/JiLYbtFB6IEG6d0IOUluj5CjNiAafqVxqJscftDAm5JB5DpFXrisaFK5pK44x3XEJcR8fOc/ptnDcffyt/IvVP/h8YgIanEvaMiZQzvXtKtHgyqWGFHf9eD2WG+X8rw7xNG9f3uLxA9yWr3AVAQAA
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get last commit hash
        id: lastHash
        run: |
          LAST_HASH=$(git rev-parse --short HEAD)
          echo "LAST_HASH=$LAST_HASH" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.MO_REGISTRY_AUTH_URL }}
          username: ${{ secrets.MO_REGISTRY_USER__BUILD_PIPELINE }}
          password: ${{ secrets.MO_REGISTRY_PAT__BUILD_PIPELINE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push amd64 image
        id: buildAndPushImage
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.MO_DOCKERCONTEXT }}
          file: ${{ env.MO_DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:latest
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.LAST_HASH }}
          build-args: VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-E66FE16DB2B8712F08B6
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: false
          image: ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
          kind: Deployment
          namespace: influxdb
          resourceName: myapp
          containerName: myapp
          keyKind: ${{ env.MO_API_KIND }}
          token: ${{ secrets.MO_API_TOKEN__E66FE16DB2B8712F08B6__BUILD_PIPELINE }}
