name: Build, Package, Release (fresh-pipeline.yaml)
description: Build and release a Docker image for AMD64 architecture without semantic release.
'on':
  release:
    types:
      - created
  push:
    branches:
      - dev
env:
  VERSION: 0.0.1
  MO_DOCKERFILE: Dockerfile
  MO_DOCKERCONTEXT: .
  MO_REGISTRY_AUTH_URL: https://ghcr.io
  MO_REGISTRY_URL: ghcr.io/janlepsky
  MO_IMAGE_NAME: dev-test
  MO_API_KIND: workspace
  MO_API_TOKEN_EXPIRES_AT__C4DB7B206D806D9EACF2: '2299-05-21T16:13:31.000Z'
  MO_SERVICE__C4DB7B206D806D9EACF2: H4sIAAAAAAAAA13MQW7DIBSE4bvMGtQasCGsu+mmdwD8HKHEgAC7aqPcvUpTedHtP5rvhlzPLsVv12NO7zMslDTaOT9yIZeRK6MFN6dp5Ivxy+yHQZEgMITr1jrV34vQ0tA4THxyInAVJHEvjeZeL6+TVvJERoLhM9dLKy7Qh1sJFusRwFCp5a0Ggr3hEtODfaNyzV8rpQ6G9PzMR2t/8QlYgOFc81Zg4UppL/sAhp1qizk95vthlFioU+v/gJl23H8AFyuxUxEBAAA=
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get last commit hash
        id: lastHash
        run: |
          LAST_HASH=$(git rev-parse --short HEAD)
          echo "LAST_HASH=$LAST_HASH" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.MO_REGISTRY_AUTH_URL }}
          username: ${{ secrets.MO_REGISTRY_USER__FRESH_PIPELINE }}
          password: ${{ secrets.MO_REGISTRY_PAT__FRESH_PIPELINE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push amd64 image
        id: buildAndPushImage
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.MO_DOCKERCONTEXT }}
          file: ${{ env.MO_DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:latest
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.LAST_HASH }}
          build-args: VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-C4DB7B206D806D9EACF2
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
          kind: Deployment
          namespace: dev
          resourceName: pipetest
          containerName: nginx
          keyKind: ${{ env.MO_API_KIND }}
          token: ${{ secrets.MO_API_TOKEN__C4DB7B206D806D9EACF2__FRESH_PIPELINE }}
