name: Build, Package, Release (mogenius-build.yaml)
description: Build and release a Docker image for AMD64 architecture without semantic release.
'on':
  release:
    types:
      - created
  push:
    branches:
      - dev
env:
  VERSION: 0.0.1
  MO_DOCKERFILE: Dockerfile
  MO_DOCKERCONTEXT: .
  MO_REGISTRY_AUTH_URL: https://ghcr.io
  MO_REGISTRY_URL: ghcr.io/janlepsky
  MO_IMAGE_NAME: pda-be
  MO_API_KIND: workspace
  MO_API_TOKEN_EXPIRES_AT__EF0447E09F0769DAAEBA: '2299-06-05T08:21:41.000Z'
  MO_SERVICE__EF0447E09F0769DAAEBA: H4sIAAAAAAAAA12MTW7DIBQG7/KtjRpswD/rbrrpHR7wEqHYgMBOk0a5e+W0yqLbGc3ckcqJYvimNaT44THh2HetM4pE1ysjlG9ZWGudUMNhJK0k+96hgZu3unJ5Jgdvda/JiLYbtFB6IEG6d0IOUluj5CjNiAZfqZxrJseftDAm5JB5DpFXrisaFK5pK44x3XEOcR+/c57TbeG4+/hb+Rerf/D5xAQ0OJW0ZUygnOvbRaLBhUsNKe768XosN8FXWvLM/xYhHuft6i0eP0d9mToaAQAA
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get last commit hash
        id: lastHash
        run: |
          LAST_HASH=$(git rev-parse --short HEAD)
          echo "LAST_HASH=$LAST_HASH" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.MO_REGISTRY_AUTH_URL }}
          username: ${{ secrets.MO_REGISTRY_USER__MOGENIUS_BUILD }}
          password: ${{ secrets.MO_REGISTRY_PAT__MOGENIUS_BUILD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push amd64 image
        id: buildAndPushImage
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.MO_DOCKERCONTEXT }}
          file: ${{ env.MO_DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:latest
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.LAST_HASH }}
          build-args: VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-EF0447E09F0769DAAEBA
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: false
          image: ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
          kind: Deployment
          namespace: influxdb
          resourceName: my-example
          containerName: my-example
          keyKind: ${{ env.MO_API_KIND }}
          token: ${{ secrets.MO_API_TOKEN__EF0447E09F0769DAAEBA__MOGENIUS_BUILD }}
