name: Build, Package, Release (mynewworkflow.yaml)
description: Build and release a Docker image for AMD64 architecture without semantic release.
'on':
  release:
    types:
      - created
  push:
    branches:
      - dev
env:
  VERSION: 0.0.1
  MO_DOCKERFILE: Dockerfile
  MO_DOCKERCONTEXT: .
  MO_REGISTRY_AUTH_URL: https://ghcr.io
  MO_REGISTRY_URL: ghcr.io/janlepsky
  MO_IMAGE_NAME: theimage
  MO_API_KIND: workspace
  MO_API_TOKEN_EXPIRES_AT__DE5A34B38F15F2D1B5F4: '2026-09-01T14:47:31.000Z'
  MO_SERVICE__DE5A34B38F15F2D1B5F4: H4sIAAAAAAAAA03NvW7DIBQF4Hc5M6i1gZgwZ+nSsfu1uUQoNiCwm6ZR3r1KIkVdP52fK3I9Uoq/tMacPjwctLID0Whkr4KR2g69tPudkcGOwY9dp7lnCEzz1lauj0rQZmeN1VJ5PUjdB5b7Tik52dEO4d16qwwEzrmeWqGJP2lhOCQ+vwgClVve6sRwV5xiug8fuMz5snBaIVDmrdIMB//SBgEq8YtriznBgUppb98dBBIt/Fj2cGvd+Pak++0xpp//CTgsl6fe/gBLBv3/EQEAAA==
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get last commit hash
        id: lastHash
        run: |
          LAST_HASH=$(git rev-parse --short HEAD)
          echo "LAST_HASH=$LAST_HASH" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.MO_REGISTRY_AUTH_URL }}
          username: ${{ secrets.MO_REGISTRY_USER__MYNEWWORKFLOW }}
          password: ${{ secrets.MO_REGISTRY_PAT__MYNEWWORKFLOW }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push amd64 image
        id: buildAndPushImage
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.MO_DOCKERCONTEXT }}
          file: ${{ env.MO_DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:latest
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.LAST_HASH }}
          build-args: ''
      - id: releaseWithMogenius-DE5A34B38F15F2D1B5F4
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
          kind: Deployment
          namespace: mynginx
          resourceName: nginx
          containerName: nginx
          keyKind: ${{ env.MO_API_KIND }}
          token: bearer ${{ secrets.MO_API_TOKEN__DE5A34B38F15F2D1B5F4__MYNEWWORKFLOW }}
