name: Build, Package, Release (shinybuildpipe.yaml)
description: Build and release a Docker image for AMD64 architecture without semantic release.
'on':
  release:
    types:
      - created
  push:
    branches:
      - dev
env:
  VERSION: 0.0.1
  MO_DOCKERFILE: Dockerfile
  MO_DOCKERCONTEXT: .
  MO_REGISTRY_AUTH_URL: https://ghcr.io
  MO_REGISTRY_URL: ghcr.io/janlepsky
  MO_IMAGE_NAME: theimage
  MO_API_KIND: workspace
  MO_API_TOKEN_EXPIRES_AT__612BB0EA09D47983EA4F: '2299-06-05T09:47:43.000Z'
  MO_SERVICE__612BB0EA09D47983EA4F: H4sIAAAAAAAAA12MQW6DMBQF7/LW/irYBjuss+mmdzDmg9wEG9mQKo1y9yqlYtHlm6eZB1KeXAzfbg0pvg/ooJU1zvUNSTU2pK2RZE9tQ6Ptx6Gva82SIeCvW1k5/yrSKMtN3VLrpCftFVOvrKHejFVrtDqxVRD4SvlSFuf5w82MDvMBIJC5pC17RvfAJcRX9szLNd1njisE4u4MByt/cA90gMCU07agg1uW8narIXDjXEKKr/t5NOY7+RRXFyJnCrObmORQVVL/K366uM/y2s8frqnq/iwBAAA=
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Get last commit hash
        id: lastHash
        run: |
          LAST_HASH=$(git rev-parse --short HEAD)
          echo "LAST_HASH=$LAST_HASH" >> $GITHUB_ENV
      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.MO_REGISTRY_AUTH_URL }}
          username: ${{ secrets.MO_REGISTRY_USER__SHINYBUILDPIPE }}
          password: ${{ secrets.MO_REGISTRY_PAT__SHINYBUILDPIPE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push amd64 image
        id: buildAndPushImage
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.MO_DOCKERCONTEXT }}
          file: ${{ env.MO_DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:latest
            ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.LAST_HASH }}
          build-args: VERSION=${{ env.VERSION }}
      - id: releaseWithMogenius-612BB0EA09D47983EA4F
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ env.MO_REGISTRY_URL }}/${{ env.MO_IMAGE_NAME }}:${{ env.VERSION }}
          kind: Deployment
          namespace: jannamespsace
          resourceName: my-container-image-2d0024
          containerName: nginx
          keyKind: ${{ env.MO_API_KIND }}
          token: bearer ${{ secrets.MO_API_TOKEN__612BB0EA09D47983EA4F__SHINYBUILDPIPE }}
